const malla = document.getElementById("malla");
const mensajeRequisitos = document.getElementById("mensajeRequisitos");

const ramosPorCiclo = {
  "1er ciclo": [
    "MATEMÁTICA I",
    "INTRODUCCIÓN A LA VIDA UNIVERSITARIA",
    "LABORATORIO DE QUÍMICA GENERAL",
    "QUÍMICA GENERAL",
    "INDIVIDUO Y MEDIO AMBIENTE",
    "INGLÉS I",
    "COMPRENSIÓN Y REDACCIÓN DE TEXTOS I"
  ],
  "2do ciclo": [
    "MATEMÁTICA II",
    "CIUDADANÍA Y REFLEXIÓN ÉTICA",
    "INGLÉS II",
    "COMPRENSIÓN Y REDACCIÓN DE TEXTOS II",
    "ESTADÍSTICA DESCRIPTIVA Y Probabilidades",
    "PRINCIPIOS DE ALGORITMOS",
    "DIBUJO PARA INGENIERÍA"
  ],
  "3er ciclo": [
    "LABORATORIO DE MECÁNICA CLÁSICA",
    "MECÁNICA CLÁSICA",
    "CÁLCULO I",
    "INVESTIGACIÓN ACADÉMICA",
    "GEOLOGÍA",
    "PLANOS Y METRADOS DE OBRAS DE CONSTRUCCIÓN",
    "INGLÉS III",
    "PROBLEMAS Y DESAFÍOS EN EL PERÚ ACTUAL"
  ],
  "4to ciclo": [
    "LABORATORIO DE MATERIALES DE CONSTRUCCIÓN",
    "MATERIALES DE CONSTRUCCIÓN",
    "FLUIDOS Y TERMODINÁMICA",
    "LABORATORIO DE FLUIDOS Y TERMODINÁMICA",
    "CÁLCULO II",
    "TOPOGRAFÍA - INGENIERIA CIVIL",
    "ESTÁTICA",
    "INGLÉS IV"
  ],
  "5to ciclo": [
    "CONSTRUCCIÓN",
    "FUNDAMENTOS DE DINÁMICA",
    "GEOMÁTICA",
    "TECNOLOGÍA DEL CONCRETO",
    "CÁLCULO AVANZADO PARA INGENIERÍA",
    "CALCULO PARA LA TOMA DE DECISIONES",
    "HERRAMIENTAS INFORMÁTICAS PARA LA TOMA DE DECISIONES"
  ],
  "6to ciclo": [
    "LABORATORIO DE ELASTICIDAD Y RESISTENCIA DE MATERIALES",
    "ELASTICIDAD Y RESISTENCIA DE MATERIALES",
    "LABORATORIO DE MECÁNICA DE FLUIDOS",
    "MECÁNICA DE FLUIDOS",
    "HERRAMIENTAS PARA LA COMUNICACIÓN EFECTIVA",
    "CONSTRUCCIONES ESPECIALES",
    "MECÁNICA DE SUELOS",
    "CURSO INTEGRADOR I – CIVIL"
  ],
  "7mo ciclo": [
    "LABORATORIO DE HIDRÁULICA DE CANALES",
    "HIDRÁULICA DE CANALES",
    "INGENIERÍA GEOTÉCNICA",
    "MODELADO DE INFORMACIÓN DE EDIFICACIONES – BIM",
    "INGENIERÍA DE CARRETERAS",
    "INSTALACIONES EN EDIFICACIONES",
    "ANÁLISIS ESTRUCTURAL I",
    "FORMACIÓN PARA LA EMPLEABILIDAD"
  ],
  "8vo ciclo": [
    "ANÁLISIS ESTRUCTURAL II",
    "HIDROLOGÍA APLICADA",
    "SEMINARIO DE INGENIERÍA CIVIL",
    "MECÁNICA DE SUELOS APLICADA",
    "ESTIMACIÓN DE COSTOS Y PLANIFICACIÓN DE OBRA",
    "ADMINISTRACIÓN Y ORGANIZACIÓN DE EMPRESAS CONSTRUCTORAS",
    "CONSTRUCCIÓN DE CARRETERAS",
    "ÉTICA PROFESIONAL"
  ],
  "9no ciclo": [
    "GESTIÓN DE PROYECTOS DE CONSTRUCCIÓN",
    "INGENIERÍA DE CIMENTACIONES",
    "PAVIMENTOS",
    "INGENIERÍA DE LOS RECURSOS HIDRÁULICOS",
    "SISTEMA INTEGRADO DE GESTIÓN EN LA CONSTRUCCIÓN",
    "FORMACIÓN PARA LA INVESTIGACIÓN – CIVIL",
    "CONCRETO ARMADO"
  ],
  "10mo ciclo": [
    "INGENIERIA SISMORRESISTENTE",
    "GESTIÓN DE PROYECTOS DE INVERSIÓN PÚBLICA",
    "TALLER DE INVESTIGACIÓN – CIVIL",
    "CURSO INTEGRADOR II – CIVIL",
    "FUNDAMENTOS DE METODOLOGÍA VDC EN EDIFICACIONES",
    "SEGURIDAD Y SALUD OCUPACIONAL EN OBRAS DE CONSTRUCCIÓN",
    "SOSTENIBILIDAD AMBIENTAL EN LA CONSTRUCCIÓN",
    "ANÁLISIS DE ESTRUCTURAS POR ELEMENTOS FINITOS",
    "MÉTODOS NUMÉRICOS",
    "ELEMENTARY BUSINESS ENGLISH"
  ]
};

const requisitos = {
  "MATEMÁTICA II": ["MATEMÁTICA I"],
  "INGLÉS II": ["INGLÉS I"],
  "COMPRENSIÓN Y REDACCIÓN DE TEXTOS II": ["COMPRENSIÓN Y REDACCIÓN DE TEXTOS I"],
  "CÁLCULO I

